### ISSUE TITLE
Mapping a case class param to Map[String,Any]?

### ISSUE THREAD

**Issue by tc** [codahale/jerkson#18]
Is it possible to map a param to Map[String,Any]?
The use case is that i have a json field called params which i just want to ignore rather than process.
Here's the breaking test case.

```
import org.junit.{Test, Assert, Before}
import com.codahale.jerkson.Json._

case class Element(title:String, params:Map[String,Any])
@Test
class JsonParserTest{
  @Test
  def testMapAny{
    val result = parse[Element]("""{"title":"foobar", "params":{"one":1,"two":2, "other": "give"}}""")
    println(result)
  }
}
```

**Comment by codahale** [comment]
What result does it give you which you weren't expecting?

**Comment by tc** [comment]
Sorry, I forgot to include the exception trace, it doesn't parse. 
If "Any" was a String, it would work, but the idea is that the params value can be a string, another map, etc.

Running JsonParserTest
java.lang.ClassNotFoundException: scala.Any
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:307)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at com.codahale.jerkson.util.CaseClassSigParser$.loadClass(CaseClassSigParser.scala:114)
    at com.codahale.jerkson.util.CaseClassSigParser$.typeRef2JavaType(CaseClassSigParser.scala:75)
    at com.codahale.jerkson.util.CaseClassSigParser$$anonfun$typeRef2JavaType$1.apply(CaseClassSigParser.scala:78)
    at com.codahale.jerkson.util.CaseClassSigParser$$anonfun$typeRef2JavaType$1.apply(CaseClassSigParser.scala:78)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:194)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:194)
    at scala.collection.immutable.List.map(List.scala:45)
    at com.codahale.jerkson.util.CaseClassSigParser$.typeRef2JavaType(CaseClassSigParser.scala:77)
    at com.codahale.jerkson.util.CaseClassSigParser$$anonfun$parse$3.apply(CaseClassSigParser.scala:66)
    at com.codahale.jerkson.util.CaseClassSigParser$$anonfun$parse$3.apply(CaseClassSigParser.scala:63)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:200)
    at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:200)
    at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
    at scala.collection.immutable.List.foreach(List.scala:45)
    at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:200)
    at scala.collection.immutable.List.flatMap(List.scala:45)
    at com.codahale.jerkson.util.CaseClassSigParser$.parse(CaseClassSigParser.scala:63)
    at com.codahale.jerkson.deser.CaseClassDeserializer.<init>(CaseClassDeserializer.scala:18)
