### ISSUE TITLE
Jerkson Fails on Case Classes that Contain a Map

### ISSUE THREAD

**Issue by lambdaknight** [codahale/jerkson#19]
The following code snippet works just fine:

``` scala
parse[Map[Int, Int]](generate(Map(1 -> 2)))
```

The following, however, doesn't, despite it seemingly being a fairly trivial extension of the above:

``` scala
case class Foo(a: Map[Int, Int])
parse[Foo](generate(Foo(Map(1 -> 2))))
```

This yields the following exception:

```
com.codahale.jerkson.ParsingException: Can not construct instance of scala.collection.immutable.Map, problem: abstract types can only be instantiated with additional type information
 at [Source: N/A; line: -1, column: -1]
    at com.codahale.jerkson.ParsingException$.apply(ParsingException.scala:17)
    at com.codahale.jerkson.Parser$class.parse(Parser.scala:75)
    at com.codahale.jerkson.Json$.parse(Json.scala:6)
    at com.codahale.jerkson.Parser$class.parse(Parser.scala:14)
    at com.codahale.jerkson.Json$.parse(Json.scala:6)
    at .<init>(<console>:12)
    at .<clinit>(<console>)
    at .<init>(<console>:11)
    at .<clinit>(<console>)
    at $export(<console>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:592)
    at scala.tools.nsc.interpreter.IMain$Request$$anonfun$10.apply(IMain.scala:828)
    at scala.tools.nsc.interpreter.Line$$anonfun$1.apply$mcV$sp(Line.scala:43)
    at scala.tools.nsc.io.package$$anon$2.run(package.scala:31)
    at java.lang.Thread.run(Thread.java:680)
Caused by: org.codehaus.jackson.map.JsonMappingException: Can not construct instance of scala.collection.immutable.Map, problem: abstract types can only be instantiated with additional type information
 at [Source: N/A; line: -1, column: -1]
    at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163)
    at org.codehaus.jackson.map.deser.StdDeserializationContext.instantiationException(StdDeserializationContext.java:212)
    at org.codehaus.jackson.map.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:97)
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2372)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1162)
    at com.codahale.jerkson.deser.CaseClassDeserializer$$anonfun$deserialize$2.apply(CaseClassDeserializer.scala:40)
    at com.codahale.jerkson.deser.CaseClassDeserializer$$anonfun$deserialize$2.apply(CaseClassDeserializer.scala:33)
    at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:34)
    at scala.collection.mutable.ArrayOps.foreach(ArrayOps.scala:38)
    at com.codahale.jerkson.deser.CaseClassDeserializer.deserialize(CaseClassDeserializer.scala:33)
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2372)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1162)
    at com.codahale.jerkson.Parser$class.parse(Parser.scala:72)
    ... 17 more
```

**Comment by lambdaknight** [comment]
NM.  Pretty sure this is just type erasure biting me in the ass.
