### ISSUE TITLE
Parsing fails for Maps that contain unmarshalled keys

### ISSUE THREAD

**Issue by aryairani** [codahale/jerkson#44]
The following code snippets works just fine:

```
import java.net.URL
parse[Map[String,URL]](generate(Map(new URL("http://foo.com") -> new URL("http://foo.com"))))
//res: Map[String,java.net.URL] = Map(http://foo.com -> http://foo.com)
```

But the following:

```
import java.net.URL
parse[Map[URL,URL]](generate(Map(new URL("http://foo.com") -> new URL("http://foo.com"))))
```

throws

```
org.codehaus.jackson.map.JsonMappingException: Can not construct instance of scala.collection.immutable.Map, problem: abstract types can only be instantiated with additional type information
 at [Source: java.io.StringReader@1a47da2e; line: 1, column: 1]
    at org.codehaus.jackson.map.JsonMappingException.from(JsonMappingException.java:163)
    at     org.codehaus.jackson.map.deser.StdDeserializationContext.instantiationException(StdDeserializationContext.java:233)
    at org.codehaus.jackson.map.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:60)
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2704)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1315)
    at com.codahale.jerkson.Parser$class.parse(Parser.scala:83)
    ... 35 more
```

and I can't figure out how to proceed...

P.S.  Thanks for a basically awesome library!

**Comment by ghost** [comment]
+1

**Comment by aryairani** [comment]
Sweet, someone read my ticket :-)
